### PR TITLE
fix(lsp): add semantic tokens for OVERRIDES statement and bash control-flow keywords

### LINKED ISSUE #353: Bitbake-LSP server 'fails' with OVERRIDE variable and other behaviors
Dear devs, 

While using this amazing extension, I found out that are certain cases where the LSP seems to fail to highlight the information correctly. I will attach some photos so that you see what I mean, otherwise I do not see how you can see it (Let me know if there is a better way).

**Case 1**
The variable `OVERRIDES` seems to have a particular behavior when using inside of a `local.conf` or recipe. As soon as I write that particular variable, the next three (or four) lines are no longer correctly recognize. This happens only with this variable as far as I know.
code
code_1

**Case 2**
When you break some long variables like for example in this case, this will damage the highlight of the whole file. I am not sure exactly why, because for example the `SRC_URI` normally has that behavior and I do not have any problem in that case
code_2

**Case 3**
This case is maybe not that important, but the highlight of shell script has this issue where the `then` is not recognize as a keyword.
code_4

Thanks again for your time. 

Sincerely, 

Jairo M

### PR DESCRIPTION
**Pull request by aki1770-del**
## Problem

Two semantic highlighting gaps reported in #353:

**1 — OVERRIDES statement**

`OVERRIDES = "linux:arm:pn-foo"` is parsed by tree-sitter-bitbake as an
`overrides_statement` node, not a `variable_assignment`. As a result:

- The `OVERRIDES` keyword has node type `'OVERRIDES'` (not `'identifier'`),
  so `isVariableReference()` does not match it — it receives no semantic token
  and is not highlighted as a variable declaration.
- The override names inside the string (`linux`, `arm`, `pn-foo`) are identifiers
  whose parent is `'overrides_statement'`, not `'override'`. `utils.ts isOverride()`
  does not match `'overrides_statement'` — they receive no semantic token and are
  not highlighted as override tokens.

**2 — Bash control-flow keywords**

Bash keywords such as `then`, `if`, `fi`, `else`, `do`, `done` have node types
matching their text in tree-sitter-bash. `getBashParsedTokens()` only handled
`variable_name` and `command_name`, leaving all control-flow keywords unhighlighted
inside BitBake shell functions.

## Fix

**`server/src/tree-sitter/utils.ts`** — `isOverride()`:
Add `parentType === 'overrides_statement'` so override names inside the OVERRIDES
value are highlighted as `operator+readonly` tokens.

**`server/src/semanticTokens.ts`** — `getBitBakeParsedTokens()`:
Add `node.type === 'OVERRIDES'` check to emit a `variable+declaration` token for
the OVERRIDES keyword itself.

**`server/src/semanticTokens.ts`** — `getBashParsedTokens()`:
Add `BASH_KEYWORDS` set check to emit `keyword` tokens for `if`, `then`, `else`,
`elif`, `fi`, `for`, `while`, `until`, `do`, `done`, `case`, `in`, `esac`.

## Tests

Two new test cases in `semanticTokens.test.ts`:
- `OVERRIDES = "linux:arm:pn-foo"` — verifies variable and operator tokens
- Shell function with `if [...]; then ... fi` — verifies keyword tokens for all three

Note: Case 2 (multi-line variable continuation breaking whole-file highlight) appears
to be a tree-sitter-bitbake grammar issue. It is not addressed in this PR.

Fixes #353

### CODE REVIEW

**Comment by deribaucourt** [comment]
Thanks for your contribution!
Could you point to the staging branch instead of main? staging is our development branch, while main represents the latest release.
@idillon-sfl I assigned you for review since you were the original author of this part of the code. Could you take a moment to review it?

**Comment by aki1770-del** [comment]
Thanks for the review and for assigning @idillon-sfl.

Updated the PR target to `staging`. Apologies for the stacked branches — the `fix/lsp-override-semantic-tokens-issue-353` branch contains only this commit and is now correctly based on `staging`.

File: server/src/semanticTokens.ts [hunk 1]
```diff
@@ -110,6 +110,23 @@ export function getBashParsedTokens (uri: string): ParsedToken[] {
       })
     }
 
+    // Bash control-flow keywords have node types matching their text in the
+    // tree-sitter-bash grammar (e.g. 'if', 'then', 'else', 'fi', 'for',
+    // 'while', 'do', 'done', 'case', 'in', 'esac', 'elif').
+    const BASH_KEYWORDS = new Set([
```
Comment (rawaha-e) [inline server/src/semanticTokens.ts]: `BASH_KEYWORDS` is defined inside `forEach` which reconstructs the `Set` on every node traversal. This can be moved to module scope.

**Review by rawaha-e — CHANGES_REQUESTED** [review]

**Comment by aki1770-del** [comment]
Good catch — moved to module scope. Thanks.

**Comment by aki1770-del** [comment]
Thank you, rawaha-e — that was a real improvement. Reconstructing the Set on every node traversal was wasteful and completely unnecessary; I should have caught it before submitting. I appreciate the careful review.

**Comment by deribaucourt** [comment]
LGTM. @rawaha-e Please update your review if you think this is fine now.

**Review by rawaha-e — APPROVED** [review]
LGTM
